std = "lua51"
max_line_length = false

ignore = {
    "212/self",
}

globals = {
  "ClassicPlates",
  "ClassicPlatesDB",
  "SendSystemMessage",
  "C_NamePlate.GetNamePlateForUnit",
  "SetCVar",
  "GetCVar",
  "tContains",
  "UnitIsUnit",
  "UnitEffectiveLevel",
  "UnitExists",
  "UnitClass", 
  "UnitHealth", 
  "UnitHealthMax", 
  "GetUnitName", 
  "UnitIsFriend", 
  "UnitIsEnemy",
  "UnitIsPlayer",
  "UnitClassification", 
  "UnitCanAttack", 
  "UnitPlayerControlled", 
  "UnitIsTapDenied", 
  "GetQuestGreenRange", 
  "UnitThreatSituation",
  "UnitReaction", 
  "GetRaidTargetIndex", 
  "SetRaidTargetIconTexture", 
  "C_NamePlate.GetNamePlates",
  "CastBar_UpdateIsShown",
  "CastBar_SetUnit",
  "CastBar_Create",
  "UnitCastingInfo", 
  "UnitChannelInfo",
  "GetTime",
  "CreateFrame",
  "CUSTOM_CLASS_COLORS",
  "RAID_CLASS_COLORS",
  "NAMEPLATE_FONT",
  "NAMEPLATE_SPELLCAST_FONT",
  "InterfaceOptionsNamesPanel",
  "pairs",
  "ipairs",
  "tonumber",
  "format",
  "_G",
}
