std = "lua51"
max_line_length = false

ignore = {
  "212/self",
}

globals = {
  "ClassicPlates",
  "ClassicPlatesDB",
  "NamePlateMixin",
  "CastBarMixin",
  "C_NamePlate.GetNamePlateForUnit",
  "C_NamePlate.GetNamePlates",
  "SetCVar",
  "GetCVar",
  "tContains",
  "UnitEffectiveLevel",
  "UnitExists",
  "UnitClass",
  "UnitHealth",
  "UnitHealthMax",
  "UnitClassification",
  "UnitCanAttack",
  "UnitPlayerControlled",
  "UnitThreatSituation",
  "UnitReaction",
  "UnitTreatAsPlayerForDisplay",
  "UnitCastingInfo",
  "UnitChannelInfo",
  "UnitIsUnit",
  "UnitIsFriend",
  "UnitIsPlayer",
  "UnitIsTapDenied",
  "GetTime",
  "GetUnitName",
  "GetQuestGreenRange",
  "GetRaidTargetIndex",
  "SetRaidTargetIconTexture",
  "CreateFrame",
  "RAID_CLASS_COLORS",
  "HIGHLIGHT_FONT_COLOR",
  "GRAY_FONT_COLOR",
  "InterfaceOptionsNamesPanel",
}
